### ISSUE TITLE
How to config 

### ISSUE THREAD

**Issue by assad-ua** [dwave-examples/factoring#40]
Hi, sorry to ask a silly question. How to add user configuration. i dont have any idea.
![Screenshot (70)](https://user-images.githubusercontent.com/75535649/148114559-533174f0-0156-410d-b00b-26b8f309b52c.png)

**Comment by hhtong** [comment]
Hi @assad-ua, you'll need to have a Leap account to run this example. You can sign up for an account here: https://cloud.dwavesys.com/leap/signup/.
 
In your Leap account, you can get an API token which will give you access to the QPU via the SAPI endpoint. There are multiple ways to use your API token and they are all described in the following documentation:  https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html#table-token-config. 

Alternatively, you can also run this code without any configurations by using the Leap IDE once you've signed in: https://ide.dwavesys.io/workspaces/.

Hope this helps! Feel free to reach out again if you have more questions.

**Comment by assad-ua** [comment]
Hi, Thanks hhtong!
It worked.
